### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by BlackEagleEF** [GeRaged/MLGHelper#1]
PLEASE CHANGE THIS

> if (cord == 23) {
        mlg = "Springen";
      } else if (cord == 24) {
        mlg = "Laufen";
      } else if (cord == 25) {
        mlg = "Funktioniert nicht";
      } else if (cord == 26) {
        mlg = "Beides";
      } else if (cord == 27) {
        mlg = "Laufen";
      } else if (cord == 28) {
        mlg = "Springen";
      } else if (cord == 29) {
        mlg = "Laufen";
      } else if (cord == 30) {
        mlg = "Springen";
      } else if (cord == 31) {
        mlg = "Springen";
      } else if (cord == 32) {
        mlg = "Funktioniert nicht";
      } else if (cord == 33) {
        mlg = "Beides";
      } else if (cord == 34) {
        mlg = "Laufen";
      } else if (cord == 35) {
        mlg = "Springen";
      } else if (cord == 36) {
        mlg = "Laufen";
      } else if (cord == 37) {
        mlg = "Springen";
      } else if (cord == 38) {
        mlg = "Laufen";
      } else if (cord == 39) {
        mlg = "Springen";
      } else if (cord == 40) {
        mlg = "Laufen";
      } else if (cord == 41) {
        mlg = "Springen";
      } else if (cord == 42) {
        mlg = "Laufen";
      } else if (cord == 43) {
        mlg = "Springen";
      } else if (cord == 44) {
        mlg = "Laufen";
      } else if (cord == 45) {
        mlg = "Springen";
      } else if (cord == 46) {
        mlg = "Funktioniert nicht";
      } else if (cord == 47) {
        mlg = "Beides";
      } else if (cord == 48) {
        mlg = "Funktioniert nicht";
      } else if (cord == 49) {
        mlg = "Laufen";
      } else if (cord == 50) {
        mlg = "Springen";
      } else if (cord == 51) {
        mlg = "Laufen";
      } else if (cord == 52) {
        mlg = "Springen";
      } else if (cord == 53) {
        mlg = "Laufen";
      } else if (cord == 54) {
        mlg = "Springen";
      } else if (cord == 55) {
        mlg = "Laufen";
      } else if (cord == 56) {
        mlg = "Springen";
      } else if (cord == 57) {
        mlg = "Funktioniert nicht";
      } else if (cord == 58) {
        mlg = "Laufen";
      } else if (cord == 59) {
        mlg = "Springen";
      } else if (cord == 60) {
        mlg = "Laufen";
      } else if (cord == 61) {
        mlg = "Springen";
      } else if (cord == 62) {
        mlg = "Laufen";
      } else if (cord == 63) {
        mlg = "Springen";
      } else if (cord == 64) {
        mlg = "Funktioniert nicht";
      } else if (cord == 65) {
        mlg = "Laufen";
      } else if (cord == 66) {
        mlg = "Springen";
      } else if (cord == 67) {
        mlg = "Laufen";
      } else if (cord == 68) {
        mlg = "Springen";
      } else if (cord == 69) {
        mlg = "Laufen";
      } else if (cord == 70) {
        mlg = "Funktioniert nicht";
      } else if (cord == 71) {
        mlg = "Springen";
      } else if (cord == 72) {
        mlg = "Laufen";
      } else if (cord == 73) {
        mlg = "Springen";
      } else if (cord == 74) {
        mlg = "Laufen";
      } else if (cord == 75) {
        mlg = "Funktioniert nicht";
      } else if (cord == 76) {
        mlg = "Springen";
      } else if (cord == 77) {
        mlg = "Laufen";
      } else if (cord == 78) {
        mlg = "Springen";
      } else if (cord == 79) {
        mlg = "Laufen";
      } else if (cord == 80) {
        mlg = "Funktioniert nicht";
      } else if (cord == 81) {
        mlg = "Springen";
      } else if (cord == 82) {
        mlg = "Laufen";
      } else if (cord == 83) {
        mlg = "Springen";
      } else if (cord == 84) {
        mlg = "Funktioniert nicht";
      } else if (cord == 85) {
        mlg = "Laufen";
      } else if (cord == 86) {
        mlg = "Springen";
      } else if (cord == 87) {
        mlg = "Laufen";
      } else if (cord == 88) {
        mlg = "Funktioniert nicht";
      } else if (cord == 89) {
        mlg = "Springen";
      } else if (cord == 90) {
        mlg = "Funktioniert nicht";
      } else if (cord == 91) {
        mlg = "Springen";
      } else if (cord == 92) {
        mlg = "Funktioniert nicht";
      } else if (cord == 93) {
        mlg = "Laufen";
      } else if (cord == 94) {
        mlg = "Springen";
      } else if (cord == 95) {
        mlg = "Laufen";
      } else if (cord == 96) {
        mlg = "Funktioniert nicht";
      } else if (cord == 97) {
        mlg = "Springen";
      } else if (cord == 98) {
        mlg = "Laufen";
      } else if (cord == 99) {
        mlg = "Funktioniert nicht";
      } else if (cord == 100) {
        mlg = "Springen";
      } else if (cord == 101) {
        mlg = "Laufen";
      } else if (cord == 102) {
        mlg = "Springen";
      } else if (cord == 103) {
        mlg = "Funktioniert nicht";
      } else if (cord == 104) {
        mlg = "Laufen";
      } else if (cord == 105) {
        mlg = "Springen";
      } else if (cord == 106) {
        mlg = "Laufen";
      } else if (cord == 107) {
        mlg = "Funktioniert nicht";
      } else if (cord == 108) {
        mlg = "Springen";
      } else if (cord == 109) {
        mlg = "Laufen";
      } else if (cord == 110) {
        mlg = "Funktioniert nicht";
      } else if (cord == 111) {
        mlg = "Springen";
      } else if (cord == 112) {
        mlg = "Laufen";
      } else if (cord == 113) {
        mlg = "Funktioniert nicht";
      } else if (cord == 114) {
        mlg = "Springen";
      } else if (cord == 115) {
        mlg = "Laufen";
      } else if (cord == 116) {
        mlg = "Funktioniert nicht";
      } else if (cord == 117) {
        mlg = "Funktioniert nicht";
      } else if (cord == 118) {
        mlg = "Laufen";
      } else if (cord == 119) {
        mlg = "Springen";
      } else if (cord == 120) {
        mlg = "Funktioniert nicht";
      } else if (cord == 121) {
        mlg = "Laufen";
      } else if (cord == 122) {
        mlg = "Springen";
      } else if (cord == 123) {
        mlg = "Funktioniert nicht";
      } else if (cord == 124) {
        mlg = "Laufen";
      } else if (cord == 125) {
        mlg = "Springen";
      } else if (cord == 126) {
        mlg = "Funktioniert nicht";
      } else if (cord == 127) {
        mlg = "Laufen";
      } else if (cord == 128) {
        mlg = "Springen";
      } else if (cord == 129) {
        mlg = "Funktioniert nicht";
      } else if (cord == 130) {
        mlg = "Laufen";
      } else if (cord == 131) {
        mlg = "Springen";
      } else if (cord == 132) {
        mlg = "Funktioniert nicht";
      } else if (cord == 133) {
        mlg = "Funktioniert nicht";
      } else if (cord == 134) {
        mlg = "Springen";
      } else if (cord == 135) {
        mlg = "Laufen";
      } else if (cord == 136) {
        mlg = "Funktioniert nicht";
      } else if (cord == 137) {
        mlg = "Springen";
      } else if (cord == 138) {
        mlg = "Laufen";
      } else if (cord == 139) {
        mlg = "Funktioniert nicht";
      } else if (cord == 140) {
        mlg = "Springen";
      } else if (cord == 141) {
        mlg = "Funktioniert nicht";
      } else if (cord == 142) {
        mlg = "Laufen";
      } else if (cord == 143) {
        mlg = "Springen";
      } else if (cord == 144) {
        mlg = "Funktioniert nicht";
      } else if (cord == 145) {
        mlg = "Laufen";
      } else if (cord == 146) {
        mlg = "Springen";
      } else if (cord == 147) {
        mlg = "Funktioniert nicht";
      } else if (cord == 148) {
        mlg = "Laufen";
      } else if (cord == 149) {
        mlg = "Funktioniert nicht";
      } else if (cord == 150) {
        mlg = "Springen";
      } else if (cord == 151) {
        mlg = "Laufen";
      } else if (cord == 152) {
        mlg = "Funktioniert nicht";
      } else if (cord == 153) {
        mlg = "Springen";
      } else if (cord == 154) {
        mlg = "Laufen";
      } else if (cord == 155) {
        mlg = "Funktioniert nicht";
      } else if (cord == 156) {
        mlg = "Springen";
      }
    } else {
      if (cord == 23) {
        mlg = "Jump";
      } else if (cord == 24) {
        mlg = "Walk";
      } else if (cord == 25) {
        mlg = "Don't work";
      } else if (cord == 26) {
        mlg = "Both";
      } else if (cord == 27) {
        mlg = "Walk";
      } else if (cord == 28) {
        mlg = "Jump";
      } else if (cord == 29) {
        mlg = "Walk";
      } else if (cord == 30) {
        mlg = "Jump";
      } else if (cord == 31) {
        mlg = "Jump";
      } else if (cord == 32) {
        mlg = "Don't work";
      } else if (cord == 33) {
        mlg = "Both";
      } else if (cord == 34) {
        mlg = "Walk";
      } else if (cord == 35) {
        mlg = "Jump";
      } else if (cord == 36) {
        mlg = "Walk";
      } else if (cord == 37) {
        mlg = "Jump";
      } else if (cord == 38) {
        mlg = "Walk";
      } else if (cord == 39) {
        mlg = "Jump";
      } else if (cord == 40) {
        mlg = "Walk";
      } else if (cord == 41) {
        mlg = "Jump";
      } else if (cord == 42) {
        mlg = "Walk";
      } else if (cord == 43) {
        mlg = "Jump";
      } else if (cord == 44) {
        mlg = "Walk";
      } else if (cord == 45) {
        mlg = "Jump";
      } else if (cord == 46) {
        mlg = "Don't work";
      } else if (cord == 47) {
        mlg = "Both";
      } else if (cord == 48) {
        mlg = "Don't work";
      } else if (cord == 49) {
        mlg = "Walk";
      } else if (cord == 50) {
        mlg = "Jump";
      } else if (cord == 51) {
        mlg = "Walk";
      } else if (cord == 52) {
        mlg = "Jump";
      } else if (cord == 53) {
        mlg = "Walk";
      } else if (cord == 54) {
        mlg = "Jump";
      } else if (cord == 55) {
        mlg = "Walk";
      } else if (cord == 56) {
        mlg = "Jump";
      } else if (cord == 57) {
        mlg = "Don't work";
      } else if (cord == 58) {
        mlg = "Walk";
      } else if (cord == 59) {
        mlg = "Jump";
      } else if (cord == 60) {
        mlg = "Walk";
      } else if (cord == 61) {
        mlg = "Jump";
      } else if (cord == 62) {
        mlg = "Walk";
      } else if (cord == 63) {
        mlg = "Jump";
      } else if (cord == 64) {
        mlg = "Don't work";
      } else if (cord == 65) {
        mlg = "Walk";
      } else if (cord == 66) {
        mlg = "Jump";
      } else if (cord == 67) {
        mlg = "Walk";
      } else if (cord == 68) {
        mlg = "Jump";
      } else if (cord == 69) {
        mlg = "Walk";
      } else if (cord == 70) {
        mlg = "Don't work";
      } else if (cord == 71) {
        mlg = "Jump";
      } else if (cord == 72) {
        mlg = "Walk";
      } else if (cord == 73) {
        mlg = "Jump";
      } else if (cord == 74) {
        mlg = "Walk";
      } else if (cord == 75) {
        mlg = "Don't work";
      } else if (cord == 76) {
        mlg = "Jump";
      } else if (cord == 77) {
        mlg = "Walk";
      } else if (cord == 78) {
        mlg = "Jump";
      } else if (cord == 79) {
        mlg = "Walk";
      } else if (cord == 80) {
        mlg = "Don't work";
      } else if (cord == 81) {
        mlg = "Jump";
      } else if (cord == 82) {
        mlg = "Walk";
      } else if (cord == 83) {
        mlg = "Jump";
      } else if (cord == 84) {
        mlg = "Don't work";
      } else if (cord == 85) {
        mlg = "Walk";
      } else if (cord == 86) {
        mlg = "Jump";
      } else if (cord == 87) {
        mlg = "Walk";
      } else if (cord == 88) {
        mlg = "Don't work";
      } else if (cord == 89) {
        mlg = "Jump";
      } else if (cord == 90) {
        mlg = "Don't work";
      } else if (cord == 91) {
        mlg = "Jump";
      } else if (cord == 92) {
        mlg = "Don't work";
      } else if (cord == 93) {
        mlg = "Walk";
      } else if (cord == 94) {
        mlg = "Jump";
      } else if (cord == 95) {
        mlg = "Walk";
      } else if (cord == 96) {
        mlg = "Don't work";
      } else if (cord == 97) {
        mlg = "Jump";
      } else if (cord == 98) {
        mlg = "Walk";
      } else if (cord == 99) {
        mlg = "Don't work";
      } else if (cord == 100) {
        mlg = "Jump";
      } else if (cord == 101) {
        mlg = "Walk";
      } else if (cord == 102) {
        mlg = "Jump";
      } else if (cord == 103) {
        mlg = "Don't work";
      } else if (cord == 104) {
        mlg = "Walk";
      } else if (cord == 105) {
        mlg = "Jump";
      } else if (cord == 106) {
        mlg = "Walk";
      } else if (cord == 107) {
        mlg = "Don't work";
      } else if (cord == 108) {
        mlg = "Jump";
      } else if (cord == 109) {
        mlg = "Walk";
      } else if (cord == 110) {
        mlg = "Don't work";
      } else if (cord == 111) {
        mlg = "Jump";
      } else if (cord == 112) {
        mlg = "Walk";
      } else if (cord == 113) {
        mlg = "Don't work";
      } else if (cord == 114) {
        mlg = "Jump";
      } else if (cord == 115) {
        mlg = "Walk";
      } else if (cord == 116) {
        mlg = "Don't work";
      } else if (cord == 117) {
        mlg = "Don't work";
      } else if (cord == 118) {
        mlg = "Walk";
      } else if (cord == 119) {
        mlg = "Jump";
      } else if (cord == 120) {
        mlg = "Don't work";
      } else if (cord == 121) {
        mlg = "Walk";
      } else if (cord == 122) {
        mlg = "Jump";
      } else if (cord == 123) {
        mlg = "Don't work";
      } else if (cord == 124) {
        mlg = "Walk";
      } else if (cord == 125) {
        mlg = "Jump";
      } else if (cord == 126) {
        mlg = "Don't work";
      } else if (cord == 127) {
        mlg = "Walk";
      } else if (cord == 128) {
        mlg = "Jump";
      } else if (cord == 129) {
        mlg = "Don't work";
      } else if (cord == 130) {
        mlg = "Walk";
      } else if (cord == 131) {
        mlg = "Jump";
      } else if (cord == 132) {
        mlg = "Don't work";
      } else if (cord == 133) {
        mlg = "Don't work";
      } else if (cord == 134) {
        mlg = "Jump";
      } else if (cord == 135) {
        mlg = "Walk";
      } else if (cord == 136) {
        mlg = "Don't work";
      } else if (cord == 137) {
        mlg = "Jump";
      } else if (cord == 138) {
        mlg = "Walk";
      } else if (cord == 139) {
        mlg = "Don't work";
      } else if (cord == 140) {
        mlg = "Jump";
      } else if (cord == 141) {
        mlg = "Don't work";
      } else if (cord == 142) {
        mlg = "Walk";
      } else if (cord == 143) {
        mlg = "Jump";
      } else if (cord == 144) {
        mlg = "Don't work";
      } else if (cord == 145) {
        mlg = "Walk";
      } else if (cord == 146) {
        mlg = "Jump";
      } else if (cord == 147) {
        mlg = "Don't work";
      } else if (cord == 148) {
        mlg = "Walk";
      } else if (cord == 149) {
        mlg = "Don't work";
      } else if (cord == 150) {
        mlg = "Jump";
      } else if (cord == 151) {
        mlg = "Walk";
      } else if (cord == 152) {
        mlg = "Don't work";
      } else if (cord == 153) {
        mlg = "Jump";
      } else if (cord == 154) {
        mlg = "Walk";
      } else if (cord == 155) {
        mlg = "Don't work";
      } else if (cord == 156) {
        mlg = "Jump";
      }

**Comment by JumpingPxl** [comment]
welp

**Comment by GeRaged** [comment]
Der Code ist schon 2 Jahre alt habe den bisher nie geändert
